name: Cachix

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 0 * * *"

permissions: {}

jobs:
  build_stable:
    name: Build and push to Cachix (nixpkgs 25.11)
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
          submodules: 'recursive'

      - name: Install Nix
        uses: cachix/install-nix-action@fd24c48048070c1be9acd18c9d369a83f0fe94d7 # v31.8.1
        with:
          nix_path: nixpkgs=channel:nixos-25.11

      - uses: cachix/cachix-action@18cf96c7c98e048e10a83abd92116114cd8504be # v14
        with:
          name: inputactions
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Patch flake.nix
        run: sed -i -e 's/nixos-unstable/nixos-25.11/g' flake.nix

      - name: Update flake.lock
        run: nix flake update

      - name: Build
        run: nix build -L .?submodules=1#inputactions .?submodules=1#inputactions-ctl .?submodules=1#inputactions-kwin

  build_unstable:
    name: Build and push to Cachix (nixpkgs unstable)
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
          submodules: 'recursive'

      - name: Install Nix
        uses: cachix/install-nix-action@fd24c48048070c1be9acd18c9d369a83f0fe94d7 # v31.8.1
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - uses: cachix/cachix-action@18cf96c7c98e048e10a83abd92116114cd8504be # v14
        with:
          name: inputactions
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Update flake.lock
        run: nix flake update

      - name: Build
        run: nix build -L .?submodules=1#inputactions .?submodules=1#inputactions-ctl .?submodules=1#inputactions-kwin .?submodules=1#inputactions-hyprland

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
